### ISSUE TITLE
Call to LogConsumers does not precede call to LOG

### ISSUE THREAD

**Issue by mchatzip-telekom** [lipiridi/webflux-logging#1]
I found in your LoggingWebFilter class that you apply the changes to the httpLog AFTER it is already logged. I think it might be an oversight, I locally flipped the forEach(consumer::accept) line with the LOG.info(...) line and all worked as expected.

**Comment by lipiridi** [comment]
Hi @mchatzip-telekom 
Thank you for the first issue😃
This feature wasn't intended to allow modifications to the HTTP log. What I had in mind during implementation was saving the log to external storage.
Let me adjust the flow to meet your expectations and update the description. I'll notify you once it's done.

**Comment by lipiridi** [comment]
@mchatzip-telekom version 1.0.1 was released - https://central.sonatype.com/artifact/io.github.lipiridi/webflux-logging/1.0.1
